services:
  jira-ticket-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config # Mount config directory for JIRA credentials and queries
      - ./data:/app/data # Mount data directory for CSV output
    environment:
      - PYTHONUNBUFFERED=1 # Ensures Python output is sent straight to container log
      - LOG_LEVEL=INFO # Optional: configure logging level
    restart: "no" # Don't restart automatically since this is a batch job
